export const mockStakeholders = [
  { id: '1', name: 'PharmaCorp Manufacturing', type: 'manufacturer', license_number: 'MFG-2024-001' },
  { id: '2', name: 'MedSupply Distributors', type: 'distributor', license_number: 'DIST-2024-045' },
  { id: '3', name: 'HealthPlus Pharmacy', type: 'pharmacy', license_number: 'PHM-2024-789' },
  { id: '4', name: 'FDA Regulatory Authority', type: 'regulatory', license_number: 'FDA-REG-001' },
  { id: '5', name: 'BioIngredients Supplier', type: 'supplier', license_number: 'SUP-2024-123' },
];

export const mockDrugs = [
  {
    id: 'd1',
    name: 'Paracetamol',
    ndc_code: '12345-678-90',
    manufacturer_id: '1',
    dosage_form: 'Tablet',
    strength: '500mg',
    status: 'approved',
  },
  {
    id: 'd2',
    name: 'Amoxicillin',
    ndc_code: '98765-432-10',
    manufacturer_id: '1',
    dosage_form: 'Capsule',
    strength: '250mg',
    status: 'approved',
  },
];

export const mockBatches = [
  {
    id: 'b1',
    batch_number: 'BATCH-2024-001',
    drug_id: 'd1',
    drug_name: 'Paracetamol',
    manufacturer_id: '1',
    manufacturer_name: 'PharmaCorp Manufacturing',
    manufacturing_date: '2024-01-15',
    expiry_date: '2026-01-15',
    quantity: 10000,
    current_quantity: 7500,
    status: 'in_transit',
    qr_code: 'QR-BATCH-2024-001',
  },
  {
    id: 'b2',
    batch_number: 'BATCH-2024-002',
    drug_id: 'd2',
    drug_name: 'Amoxicillin',
    manufacturer_id: '1',
    manufacturer_name: 'PharmaCorp Manufacturing',
    manufacturing_date: '2024-02-10',
    expiry_date: '2026-02-10',
    quantity: 5000,
    current_quantity: 5000,
    status: 'approved',
    qr_code: 'QR-BATCH-2024-002',
  },
];

export const mockSupplyChainEvents = [
  {
    id: 'e1',
    batch_id: 'b1',
    batch_number: 'BATCH-2024-001',
    event_type: 'manufactured',
    from_stakeholder: 'PharmaCorp Manufacturing',
    to_stakeholder: '-',
    quantity: 10000,
    location: 'Mumbai, India',
    timestamp: '2024-01-15T08:00:00Z',
    blockchain_hash: 'a1b2c3d4e5f6...',
  },
  {
    id: 'e2',
    batch_id: 'b1',
    batch_number: 'BATCH-2024-001',
    event_type: 'quality_check',
    from_stakeholder: 'PharmaCorp Manufacturing',
    to_stakeholder: 'PharmaCorp Manufacturing',
    quantity: 10000,
    location: 'Mumbai, India',
    timestamp: '2024-01-16T10:30:00Z',
    blockchain_hash: 'b2c3d4e5f6g7...',
  },
  {
    id: 'e3',
    batch_id: 'b1',
    batch_number: 'BATCH-2024-001',
    event_type: 'transferred',
    from_stakeholder: 'PharmaCorp Manufacturing',
    to_stakeholder: 'MedSupply Distributors',
    quantity: 10000,
    location: 'Delhi, India',
    timestamp: '2024-01-20T14:00:00Z',
    blockchain_hash: 'c3d4e5f6g7h8...',
  },
  {
    id: 'e4',
    batch_id: 'b1',
    batch_number: 'BATCH-2024-001',
    event_type: 'received',
    from_stakeholder: 'MedSupply Distributors',
    to_stakeholder: 'MedSupply Distributors',
    quantity: 10000,
    location: 'Delhi, India',
    timestamp: '2024-01-22T09:15:00Z',
    blockchain_hash: 'd4e5f6g7h8i9...',
  },
  {
    id: 'e5',
    batch_id: 'b1',
    batch_number: 'BATCH-2024-001',
    event_type: 'transferred',
    from_stakeholder: 'MedSupply Distributors',
    to_stakeholder: 'HealthPlus Pharmacy',
    quantity: 2500,
    location: 'Bangalore, India',
    timestamp: '2024-01-25T11:00:00Z',
    blockchain_hash: 'e5f6g7h8i9j0...',
  },
];

export const mockIoTReadings = [
  { id: 'r1', sensor_id: 's1', sensor_type: 'temperature', value: 22.5, unit: '°C', timestamp: '2024-01-20T14:00:00Z', is_alert: false },
  { id: 'r2', sensor_id: 's1', sensor_type: 'temperature', value: 23.1, unit: '°C', timestamp: '2024-01-20T15:00:00Z', is_alert: false },
  { id: 'r3', sensor_id: 's1', sensor_type: 'temperature', value: 28.7, unit: '°C', timestamp: '2024-01-20T16:00:00Z', is_alert: true },
  { id: 'r4', sensor_id: 's2', sensor_type: 'humidity', value: 45.2, unit: '%', timestamp: '2024-01-20T14:00:00Z', is_alert: false },
  { id: 'r5', sensor_id: 's2', sensor_type: 'humidity', value: 47.8, unit: '%', timestamp: '2024-01-20T15:00:00Z', is_alert: false },
  { id: 'r6', sensor_id: 's3', sensor_type: 'shock', value: 2.1, unit: 'g', timestamp: '2024-01-20T14:30:00Z', is_alert: false },
  { id: 'r7', sensor_id: 's3', sensor_type: 'shock', value: 8.5, unit: 'g', timestamp: '2024-01-20T15:45:00Z', is_alert: true },
];

export const mockTamperAlerts = [
  {
    id: 'a1',
    batch_id: 'b1',
    batch_number: 'BATCH-2024-001',
    alert_type: 'temperature_violation',
    severity: 'high',
    description: 'Temperature exceeded safe threshold (>25°C)',
    location: 'Delhi, India',
    status: 'investigating',
    timestamp: '2024-01-20T16:00:00Z',
  },
  {
    id: 'a2',
    batch_id: 'b1',
    batch_number: 'BATCH-2024-001',
    alert_type: 'shock_detected',
    severity: 'medium',
    description: 'Excessive shock detected during transport (8.5g)',
    location: 'Highway EN-45',
    status: 'open',
    timestamp: '2024-01-20T15:45:00Z',
  },
];

export const mockFDASubmissions = [
  {
    id: 'f1',
    drug_name: 'Paracetamol',
    submission_type: 'annual_report',
    submission_number: 'FDA-AR-2024-001',
    submitted_by: 'PharmaCorp Manufacturing',
    submission_date: '2024-01-10',
    status: 'approved',
    approval_date: '2024-01-18',
  },
  {
    id: 'f2',
    drug_name: 'Amoxicillin',
    submission_type: 'new_drug',
    submission_number: 'FDA-ND-2024-002',
    submitted_by: 'PharmaCorp Manufacturing',
    submission_date: '2024-02-01',
    status: 'under_review',
  },
];

export const mockQualityChecks = [
  {
    id: 'q1',
    batch_number: 'BATCH-2024-001',
    check_type: 'production',
    result: 'passed',
    inspector_name: 'Dr. Rajesh Kumar',
    stakeholder_name: 'PharmaCorp Manufacturing',
    timestamp: '2024-01-16T10:30:00Z',
  },
  {
    id: 'q2',
    batch_number: 'BATCH-2024-001',
    check_type: 'incoming',
    result: 'passed',
    inspector_name: 'Ms. Priya Sharma',
    stakeholder_name: 'MedSupply Distributors',
    timestamp: '2024-01-22T09:15:00Z',
  },
];
